# These are supported funding model platforms

patreon: We hate donations
custom: https://telegram.dog/Akki_ThePro
custom: https://telegram.dog/Red_warp
website: https://lightninguserbot.blogspot.com/
